export const VALIDATOR_TYPE_ALERT = 'VALIDATOR_TYPE_ALERT';
export const VALIDATOR_TYPE_REMOVE = 'VALIDATOR_TYPE_REMOVE';
export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_COURSE = "GET_COURSE";
export const CREATE_COURSE = 'CREATE_COURSE';
export const COURSE_ERROR = 'COURSE_ERROR';
export const GET_COURSES = "GET_COURSES";
export const DELETE_COURSE = "DELETE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";

export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const SUBJECT_ERROR = 'SUBJECT_ERROR';
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';